/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZiyaratRouteImport } from './routes/ziyarat'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MajalisRouteImport } from './routes/majalis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZiyaratIdRouteImport } from './routes/ziyarat.$id'
import { Route as MajlisIdRouteImport } from './routes/majlis.$id'
import { Route as HadithIdRouteImport } from './routes/hadith.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminZiyaratRouteImport } from './routes/_admin.admin.ziyarat'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminMajalisRouteImport } from './routes/_admin.admin.majalis'
import { Route as AdminAdminBooksRouteImport } from './routes/_admin.admin.books'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin.admin.audit'
import { Route as AdminAdminArticlesRouteImport } from './routes/_admin.admin.articles'
import { Route as AdminAdminZiyaratIdEditRouteImport } from './routes/_admin.admin.ziyarat.$id.edit'
import { Route as AdminAdminMajalisIdEditRouteImport } from './routes/_admin.admin.majalis.$id.edit'
import { Route as AdminAdminBooksIdEditRouteImport } from './routes/_admin.admin.books.$id.edit'

const ZiyaratRoute = ZiyaratRouteImport.update({
  id: '/ziyarat',
  path: '/ziyarat',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MajalisRoute = MajalisRouteImport.update({
  id: '/majalis',
  path: '/majalis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZiyaratIdRoute = ZiyaratIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ZiyaratRoute,
} as any)
const MajlisIdRoute = MajlisIdRouteImport.update({
  id: '/majlis/$id',
  path: '/majlis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithIdRoute = HadithIdRouteImport.update({
  id: '/hadith/$id',
  path: '/hadith/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminZiyaratRoute = AdminAdminZiyaratRouteImport.update({
  id: '/ziyarat',
  path: '/ziyarat',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMajalisRoute = AdminAdminMajalisRouteImport.update({
  id: '/majalis',
  path: '/majalis',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBooksRoute = AdminAdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminArticlesRoute = AdminAdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminZiyaratIdEditRoute = AdminAdminZiyaratIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminAdminZiyaratRoute,
} as any)
const AdminAdminMajalisIdEditRoute = AdminAdminMajalisIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminAdminMajalisRoute,
} as any)
const AdminAdminBooksIdEditRoute = AdminAdminBooksIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminAdminBooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/books': typeof BooksRoute
  '/login': typeof LoginRoute
  '/majalis': typeof MajalisRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ziyarat': typeof ZiyaratRouteWithChildren
  '/admin': typeof AdminAdminRouteWithChildren
  '/book/$id': typeof BookIdRoute
  '/hadith/$id': typeof HadithIdRoute
  '/majlis/$id': typeof MajlisIdRoute
  '/ziyarat/$id': typeof ZiyaratIdRoute
  '/admin/articles': typeof AdminAdminArticlesRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/books': typeof AdminAdminBooksRouteWithChildren
  '/admin/majalis': typeof AdminAdminMajalisRouteWithChildren
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/ziyarat': typeof AdminAdminZiyaratRouteWithChildren
  '/admin/books/$id/edit': typeof AdminAdminBooksIdEditRoute
  '/admin/majalis/$id/edit': typeof AdminAdminMajalisIdEditRoute
  '/admin/ziyarat/$id/edit': typeof AdminAdminZiyaratIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/books': typeof BooksRoute
  '/login': typeof LoginRoute
  '/majalis': typeof MajalisRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ziyarat': typeof ZiyaratRouteWithChildren
  '/admin': typeof AdminAdminRouteWithChildren
  '/book/$id': typeof BookIdRoute
  '/hadith/$id': typeof HadithIdRoute
  '/majlis/$id': typeof MajlisIdRoute
  '/ziyarat/$id': typeof ZiyaratIdRoute
  '/admin/articles': typeof AdminAdminArticlesRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/books': typeof AdminAdminBooksRouteWithChildren
  '/admin/majalis': typeof AdminAdminMajalisRouteWithChildren
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/ziyarat': typeof AdminAdminZiyaratRouteWithChildren
  '/admin/books/$id/edit': typeof AdminAdminBooksIdEditRoute
  '/admin/majalis/$id/edit': typeof AdminAdminMajalisIdEditRoute
  '/admin/ziyarat/$id/edit': typeof AdminAdminZiyaratIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/books': typeof BooksRoute
  '/login': typeof LoginRoute
  '/majalis': typeof MajalisRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ziyarat': typeof ZiyaratRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/book/$id': typeof BookIdRoute
  '/hadith/$id': typeof HadithIdRoute
  '/majlis/$id': typeof MajlisIdRoute
  '/ziyarat/$id': typeof ZiyaratIdRoute
  '/_admin/admin/articles': typeof AdminAdminArticlesRoute
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/books': typeof AdminAdminBooksRouteWithChildren
  '/_admin/admin/majalis': typeof AdminAdminMajalisRouteWithChildren
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/ziyarat': typeof AdminAdminZiyaratRouteWithChildren
  '/_admin/admin/books/$id/edit': typeof AdminAdminBooksIdEditRoute
  '/_admin/admin/majalis/$id/edit': typeof AdminAdminMajalisIdEditRoute
  '/_admin/admin/ziyarat/$id/edit': typeof AdminAdminZiyaratIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/books'
    | '/login'
    | '/majalis'
    | '/search'
    | '/unauthorized'
    | '/ziyarat'
    | '/admin'
    | '/book/$id'
    | '/hadith/$id'
    | '/majlis/$id'
    | '/ziyarat/$id'
    | '/admin/articles'
    | '/admin/audit'
    | '/admin/books'
    | '/admin/majalis'
    | '/admin/users'
    | '/admin/ziyarat'
    | '/admin/books/$id/edit'
    | '/admin/majalis/$id/edit'
    | '/admin/ziyarat/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/books'
    | '/login'
    | '/majalis'
    | '/search'
    | '/unauthorized'
    | '/ziyarat'
    | '/admin'
    | '/book/$id'
    | '/hadith/$id'
    | '/majlis/$id'
    | '/ziyarat/$id'
    | '/admin/articles'
    | '/admin/audit'
    | '/admin/books'
    | '/admin/majalis'
    | '/admin/users'
    | '/admin/ziyarat'
    | '/admin/books/$id/edit'
    | '/admin/majalis/$id/edit'
    | '/admin/ziyarat/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/articles'
    | '/books'
    | '/login'
    | '/majalis'
    | '/search'
    | '/unauthorized'
    | '/ziyarat'
    | '/_admin/admin'
    | '/book/$id'
    | '/hadith/$id'
    | '/majlis/$id'
    | '/ziyarat/$id'
    | '/_admin/admin/articles'
    | '/_admin/admin/audit'
    | '/_admin/admin/books'
    | '/_admin/admin/majalis'
    | '/_admin/admin/users'
    | '/_admin/admin/ziyarat'
    | '/_admin/admin/books/$id/edit'
    | '/_admin/admin/majalis/$id/edit'
    | '/_admin/admin/ziyarat/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRoute
  BooksRoute: typeof BooksRoute
  LoginRoute: typeof LoginRoute
  MajalisRoute: typeof MajalisRoute
  SearchRoute: typeof SearchRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ZiyaratRoute: typeof ZiyaratRouteWithChildren
  BookIdRoute: typeof BookIdRoute
  HadithIdRoute: typeof HadithIdRoute
  MajlisIdRoute: typeof MajlisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ziyarat': {
      id: '/ziyarat'
      path: '/ziyarat'
      fullPath: '/ziyarat'
      preLoaderRoute: typeof ZiyaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majalis': {
      id: '/majalis'
      path: '/majalis'
      fullPath: '/majalis'
      preLoaderRoute: typeof MajalisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ziyarat/$id': {
      id: '/ziyarat/$id'
      path: '/$id'
      fullPath: '/ziyarat/$id'
      preLoaderRoute: typeof ZiyaratIdRouteImport
      parentRoute: typeof ZiyaratRoute
    }
    '/majlis/$id': {
      id: '/majlis/$id'
      path: '/majlis/$id'
      fullPath: '/majlis/$id'
      preLoaderRoute: typeof MajlisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/$id': {
      id: '/hadith/$id'
      path: '/hadith/$id'
      fullPath: '/hadith/$id'
      preLoaderRoute: typeof HadithIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/ziyarat': {
      id: '/_admin/admin/ziyarat'
      path: '/ziyarat'
      fullPath: '/admin/ziyarat'
      preLoaderRoute: typeof AdminAdminZiyaratRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/majalis': {
      id: '/_admin/admin/majalis'
      path: '/majalis'
      fullPath: '/admin/majalis'
      preLoaderRoute: typeof AdminAdminMajalisRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/books': {
      id: '/_admin/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminAdminBooksRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/articles': {
      id: '/_admin/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminAdminArticlesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/ziyarat/$id/edit': {
      id: '/_admin/admin/ziyarat/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/ziyarat/$id/edit'
      preLoaderRoute: typeof AdminAdminZiyaratIdEditRouteImport
      parentRoute: typeof AdminAdminZiyaratRoute
    }
    '/_admin/admin/majalis/$id/edit': {
      id: '/_admin/admin/majalis/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/majalis/$id/edit'
      preLoaderRoute: typeof AdminAdminMajalisIdEditRouteImport
      parentRoute: typeof AdminAdminMajalisRoute
    }
    '/_admin/admin/books/$id/edit': {
      id: '/_admin/admin/books/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/books/$id/edit'
      preLoaderRoute: typeof AdminAdminBooksIdEditRouteImport
      parentRoute: typeof AdminAdminBooksRoute
    }
  }
}

interface AdminAdminBooksRouteChildren {
  AdminAdminBooksIdEditRoute: typeof AdminAdminBooksIdEditRoute
}

const AdminAdminBooksRouteChildren: AdminAdminBooksRouteChildren = {
  AdminAdminBooksIdEditRoute: AdminAdminBooksIdEditRoute,
}

const AdminAdminBooksRouteWithChildren = AdminAdminBooksRoute._addFileChildren(
  AdminAdminBooksRouteChildren,
)

interface AdminAdminMajalisRouteChildren {
  AdminAdminMajalisIdEditRoute: typeof AdminAdminMajalisIdEditRoute
}

const AdminAdminMajalisRouteChildren: AdminAdminMajalisRouteChildren = {
  AdminAdminMajalisIdEditRoute: AdminAdminMajalisIdEditRoute,
}

const AdminAdminMajalisRouteWithChildren =
  AdminAdminMajalisRoute._addFileChildren(AdminAdminMajalisRouteChildren)

interface AdminAdminZiyaratRouteChildren {
  AdminAdminZiyaratIdEditRoute: typeof AdminAdminZiyaratIdEditRoute
}

const AdminAdminZiyaratRouteChildren: AdminAdminZiyaratRouteChildren = {
  AdminAdminZiyaratIdEditRoute: AdminAdminZiyaratIdEditRoute,
}

const AdminAdminZiyaratRouteWithChildren =
  AdminAdminZiyaratRoute._addFileChildren(AdminAdminZiyaratRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminArticlesRoute: typeof AdminAdminArticlesRoute
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminBooksRoute: typeof AdminAdminBooksRouteWithChildren
  AdminAdminMajalisRoute: typeof AdminAdminMajalisRouteWithChildren
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminZiyaratRoute: typeof AdminAdminZiyaratRouteWithChildren
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminArticlesRoute: AdminAdminArticlesRoute,
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminBooksRoute: AdminAdminBooksRouteWithChildren,
  AdminAdminMajalisRoute: AdminAdminMajalisRouteWithChildren,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminZiyaratRoute: AdminAdminZiyaratRouteWithChildren,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ZiyaratRouteChildren {
  ZiyaratIdRoute: typeof ZiyaratIdRoute
}

const ZiyaratRouteChildren: ZiyaratRouteChildren = {
  ZiyaratIdRoute: ZiyaratIdRoute,
}

const ZiyaratRouteWithChildren =
  ZiyaratRoute._addFileChildren(ZiyaratRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRoute,
  BooksRoute: BooksRoute,
  LoginRoute: LoginRoute,
  MajalisRoute: MajalisRoute,
  SearchRoute: SearchRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ZiyaratRoute: ZiyaratRouteWithChildren,
  BookIdRoute: BookIdRoute,
  HadithIdRoute: HadithIdRoute,
  MajlisIdRoute: MajlisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
