/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MajalisRouteImport } from './routes/majalis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MajlisIdRouteImport } from './routes/majlis.$id'
import { Route as HadithIdRouteImport } from './routes/hadith.$id'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminMajalisRouteImport } from './routes/_admin.admin.majalis'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin.admin.audit'
import { Route as AdminAdminMajalisIdEditRouteImport } from './routes/_admin.admin.majalis.$id.edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MajalisRoute = MajalisRouteImport.update({
  id: '/majalis',
  path: '/majalis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MajlisIdRoute = MajlisIdRouteImport.update({
  id: '/majlis/$id',
  path: '/majlis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithIdRoute = HadithIdRouteImport.update({
  id: '/hadith/$id',
  path: '/hadith/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMajalisRoute = AdminAdminMajalisRouteImport.update({
  id: '/majalis',
  path: '/majalis',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMajalisIdEditRoute = AdminAdminMajalisIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminAdminMajalisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/majalis': typeof MajalisRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/hadith/$id': typeof HadithIdRoute
  '/majlis/$id': typeof MajlisIdRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/majalis': typeof AdminAdminMajalisRouteWithChildren
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/majalis/$id/edit': typeof AdminAdminMajalisIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/majalis': typeof MajalisRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/hadith/$id': typeof HadithIdRoute
  '/majlis/$id': typeof MajlisIdRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/majalis': typeof AdminAdminMajalisRouteWithChildren
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/majalis/$id/edit': typeof AdminAdminMajalisIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/majalis': typeof MajalisRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/hadith/$id': typeof HadithIdRoute
  '/majlis/$id': typeof MajlisIdRoute
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/majalis': typeof AdminAdminMajalisRouteWithChildren
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/majalis/$id/edit': typeof AdminAdminMajalisIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/majalis'
    | '/search'
    | '/unauthorized'
    | '/admin'
    | '/hadith/$id'
    | '/majlis/$id'
    | '/admin/audit'
    | '/admin/majalis'
    | '/admin/users'
    | '/admin/majalis/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/majalis'
    | '/search'
    | '/unauthorized'
    | '/admin'
    | '/hadith/$id'
    | '/majlis/$id'
    | '/admin/audit'
    | '/admin/majalis'
    | '/admin/users'
    | '/admin/majalis/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/login'
    | '/majalis'
    | '/search'
    | '/unauthorized'
    | '/_admin/admin'
    | '/hadith/$id'
    | '/majlis/$id'
    | '/_admin/admin/audit'
    | '/_admin/admin/majalis'
    | '/_admin/admin/users'
    | '/_admin/admin/majalis/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  MajalisRoute: typeof MajalisRoute
  SearchRoute: typeof SearchRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  HadithIdRoute: typeof HadithIdRoute
  MajlisIdRoute: typeof MajlisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majalis': {
      id: '/majalis'
      path: '/majalis'
      fullPath: '/majalis'
      preLoaderRoute: typeof MajalisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majlis/$id': {
      id: '/majlis/$id'
      path: '/majlis/$id'
      fullPath: '/majlis/$id'
      preLoaderRoute: typeof MajlisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/$id': {
      id: '/hadith/$id'
      path: '/hadith/$id'
      fullPath: '/hadith/$id'
      preLoaderRoute: typeof HadithIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/majalis': {
      id: '/_admin/admin/majalis'
      path: '/majalis'
      fullPath: '/admin/majalis'
      preLoaderRoute: typeof AdminAdminMajalisRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/majalis/$id/edit': {
      id: '/_admin/admin/majalis/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/majalis/$id/edit'
      preLoaderRoute: typeof AdminAdminMajalisIdEditRouteImport
      parentRoute: typeof AdminAdminMajalisRoute
    }
  }
}

interface AdminAdminMajalisRouteChildren {
  AdminAdminMajalisIdEditRoute: typeof AdminAdminMajalisIdEditRoute
}

const AdminAdminMajalisRouteChildren: AdminAdminMajalisRouteChildren = {
  AdminAdminMajalisIdEditRoute: AdminAdminMajalisIdEditRoute,
}

const AdminAdminMajalisRouteWithChildren =
  AdminAdminMajalisRoute._addFileChildren(AdminAdminMajalisRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminMajalisRoute: typeof AdminAdminMajalisRouteWithChildren
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminMajalisRoute: AdminAdminMajalisRouteWithChildren,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  MajalisRoute: MajalisRoute,
  SearchRoute: SearchRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  HadithIdRoute: HadithIdRoute,
  MajlisIdRoute: MajlisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
